server.port=8082
spring.application.name=auth-service

jwt.secret=${JWT_SECRET:4izvZR+2YQXQH21kTF/FsQtacW1z79eLOhKPMUicrdM=}
jwt.expiration=86400000

telegram.bot.token=${TELEGRAM_BOT_TOKEN:8058923875:AAGeZ62JRagwoesrjMRH6wy_i8fgz8tdKd4}

spring.datasource.url=jdbc:postgresql://postgres:5432/task_db
spring.datasource.username=${POSTGRES_USER:taskuser}
spring.datasource.password=${POSTGRES_PASSWORD:password123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=public
spring.flyway.default-schema=public
spring.flyway.validate-on-migrate=false

logging.level.root=INFO
logging.level.com.example.authservice=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.file.name=/app/logs/auth-service.log

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
spring.security.filter.dispatcher-types=REQUEST,ERROR,ASYNC

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

telegram.auth.expiration=300000