server.port=8082
spring.application.name=auth-service

jwt.secret=yourVerySecretKey123456789013377
jwt.expiration=86400000

telegram.bot.token=${TELEGRAM_BOT_TOKEN:8058923875:AAGeZ62JRagwoesrjMRH6wy_i8fgz8tdKd4}

logging.level.root=INFO
logging.level.com.example.authservice=DEBUG
logging.file.name=logs/auth-service.log

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
spring.security.filter.dispatcher-types=REQUEST,ERROR,ASYNC

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

telegram.auth.expiration=300000

spring.web.cors.allowed-origins="*"
spring.web.cors.allowed-methodss="*"
spring.web.cors.allowed-headers="*"
