spring.datasource.url=jdbc:postgresql://postgres:5432/notifybot
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.schemas=public

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.group-id=auth-service-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://auth-service:8082/api

jwt.secret=your_jwt_secret_key_which_should_be_long_and_secure
jwt.expiration=86400000

logging.level.org.springframework=INFO
logging.level.com.notifybot=DEBUG

server.port=8082