spring.datasource.url=jdbc:postgresql://postgres:5432/notifybot
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.schemas=public

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.group-id=notification-service-group
spring.kafka.consumer.auto-offset-reset=earliest

logging.level.org.springframework=INFO
logging.level.com.notifybot=DEBUG

server.port=8083