spring.application.name=api-gateway
spring.cloud.gateway.enabled=true

#Route to task-service
spring.cloud.gateway.routes[0].id=task-service
spring.cloud.gateway.routes[0].uri=http://task-service:8082
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/tasks/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

#Route to auth-service
spring.cloud.gateway.routes[1].id=auth-service
spring.cloud.gateway.routes[1].uri=http://auth-service:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/auth/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

#Route to analytics-service
spring.cloud.gateway.routes[2].id=analytics-service
spring.cloud.gateway.routes[2].uri=http://analytics-service:8084
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/analytics/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1