server {
    listen 80 default_server;
    listen 443 ssl default_server;
    ssl_certificate /etc/letsencrypt/live/api.notify-task-bot.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.notify-task-bot.ru/privkey.pem;
    server_name _;

    location / {
        return 404;
    }
}