server {
    listen 443 ssl;
    server_name bot.notify-task-bot.ru;

    ssl_certificate /etc/letsencrypt/live/bot.notify-task-bot.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bot.notify-task-bot.ru/privkey.pem;

    location /webhook {
        proxy_pass http://telegram-bot:8085;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}