spring:
  application:
    name: notify-bot

bot:
  token: ${BOT_TOKEN:7738261557:AAGdmoDF1_80OtRdTPZzU-gB5rC449SrIDc}
  username: ${BOT_USERNAME:MacanSwag_bot}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: logs/notify-bot.log
  level:
    root: INFO
    com.example.notifybot: DEBUG