spring.application.name=notify-bot
server.port=8084

bot.token=8058923875:AAGeZ62JRagwoesrjMRH6wy_i8fgz8tdKd4
bot.username=QwikTaskBot

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.file.name=logs/notify-bot.log
logging.level.root=INFO
logging.level.com.example.telegrambot=DEBUG

website.url=https://front.notify-task-bot.ru
webapp.auth-redirect-path=/api/v1/auth/telegram
telegram.webapp.theme=dark
telegram.webapp.expand=true

api.base-url=http://api-gateway:8080/api/v1