spring.application.name=notify-bot

bot.token=${BOT_TOKEN:8058923875:AAGeZ62JRagwoesrjMRH6wy_i8fgz8tdKd4}
bot.username=${BOT_USERNAME:QwikTaskBot}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.file.name=logs/notify-bot.log
logging.level.root=INFO
logging.level.com.example.telegrambot=DEBUG

website.url=https://notify-task-bot.onrender.com
webapp.auth-redirect-path=/api/v1/auth/telegram
telegram.webapp.theme: dark
telegram.webapp.expand: true

api.base-url=http://localhost:8080/api/v1
